/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PageRouteImport } from './routes/$page'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SearchIndexRouteImport } from './routes/search/index'
import { Route as SearchCollectionRouteImport } from './routes/search/$collection'
import { Route as ProductHandleRouteImport } from './routes/product/$handle'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PageRoute = PageRouteImport.update({
  id: '/$page',
  path: '/$page',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchIndexRoute = SearchIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SearchRoute,
} as any)
const SearchCollectionRoute = SearchCollectionRouteImport.update({
  id: '/$collection',
  path: '/$collection',
  getParentRoute: () => SearchRoute,
} as any)
const ProductHandleRoute = ProductHandleRouteImport.update({
  id: '/product/$handle',
  path: '/product/$handle',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$page': typeof PageRoute
  '/search': typeof SearchRouteWithChildren
  '/product/$handle': typeof ProductHandleRoute
  '/search/$collection': typeof SearchCollectionRoute
  '/search/': typeof SearchIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$page': typeof PageRoute
  '/product/$handle': typeof ProductHandleRoute
  '/search/$collection': typeof SearchCollectionRoute
  '/search': typeof SearchIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$page': typeof PageRoute
  '/search': typeof SearchRouteWithChildren
  '/product/$handle': typeof ProductHandleRoute
  '/search/$collection': typeof SearchCollectionRoute
  '/search/': typeof SearchIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$page'
    | '/search'
    | '/product/$handle'
    | '/search/$collection'
    | '/search/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$page' | '/product/$handle' | '/search/$collection' | '/search'
  id:
    | '__root__'
    | '/'
    | '/$page'
    | '/search'
    | '/product/$handle'
    | '/search/$collection'
    | '/search/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PageRoute: typeof PageRoute
  SearchRoute: typeof SearchRouteWithChildren
  ProductHandleRoute: typeof ProductHandleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$page': {
      id: '/$page'
      path: '/$page'
      fullPath: '/$page'
      preLoaderRoute: typeof PageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/': {
      id: '/search/'
      path: '/'
      fullPath: '/search/'
      preLoaderRoute: typeof SearchIndexRouteImport
      parentRoute: typeof SearchRoute
    }
    '/search/$collection': {
      id: '/search/$collection'
      path: '/$collection'
      fullPath: '/search/$collection'
      preLoaderRoute: typeof SearchCollectionRouteImport
      parentRoute: typeof SearchRoute
    }
    '/product/$handle': {
      id: '/product/$handle'
      path: '/product/$handle'
      fullPath: '/product/$handle'
      preLoaderRoute: typeof ProductHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SearchRouteChildren {
  SearchCollectionRoute: typeof SearchCollectionRoute
  SearchIndexRoute: typeof SearchIndexRoute
}

const SearchRouteChildren: SearchRouteChildren = {
  SearchCollectionRoute: SearchCollectionRoute,
  SearchIndexRoute: SearchIndexRoute,
}

const SearchRouteWithChildren =
  SearchRoute._addFileChildren(SearchRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PageRoute: PageRoute,
  SearchRoute: SearchRouteWithChildren,
  ProductHandleRoute: ProductHandleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
